version: '2'

services:
  db:
    image: 'postgres:15.1-alpine'
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
